customer_list:
  path: /api/customers
  controller: App\Controller\CustomerController:indexAction
  methods: [GET]

customer_create:
  path: /api/customers
  controller: App\Controller\CustomerController:createAction
  methods: [POST]

product_list:
  path: /api/products
  controller: App\Controller\ProductController:indexAction
  methods: [GET]

product_create:
  path: /api/products
  controller: App\Controller\ProductController:createAction
  methods: [POST]

cart_show:
  path: /api/customer/{id}/cart
  controller: App\Controller\CartController:showAction
  methods: [GET]
  requirements:
    id: '\d+'

cart_create:
  path: /api/customer/cart
  controller: App\Controller\CartController:createAction
  methods: [POST]

cart_delete:
  path: /api/customer/{customerId}/cart/{cartId}
  controller: App\Controller\CartController:deleteAction
  methods: [DELETE]
  requirements:
    customerId: '\d+'
    cartId: '\d+'

cart_update:
  path: /api/customer/{customerId}/cart
  controller: App\Controller\CartController:updateAction
  methods: [PATCH]
  requirements:
    customerId: '\d+'